apiVersion: v1
kind: Service
metadata:
  name: genai-app-service
  namespace: genai-project
spec:
  type: NodePort
  selector:
    app: genai
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30088
      
